
(function(){var h=true,i=null,j=false,aa=(new Date).getTime(),ba=function(a){var b=(new Date).getTime()-aa;b="&dtd="+(b<1E4?b:"M");return a+b};var k=this,ca=function(a,b,c){a=a.split(".");c=c||k;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)if(!a.length&&b!==undefined)c[d]=b;else c=c[d]?c[d]:(c[d]={})},l=function(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";
if(!(a instanceof Object)&&(Object.prototype.toString.call(a)=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call")))return"function"}else return"null";else if(b=="function"&&typeof a.call=="undefined")return"object";return b},m=function(a){return l(a)=="array"},da=function(a){var b=l(a);return b=="array"||b=="object"&&typeof a.length=="number"},n=function(a){return typeof a=="string"},ea=function(a){a=l(a);return a=="object"||
a=="array"||a=="function"},p=function(a,b){var c=b||k;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(c,e)}}else return function(){return a.apply(c,arguments)}},q=function(a,b,c){ca(a,b,c)},fa=function(a,b,c){a[b]=c};var r=function(a,b){var c=parseFloat(a);return isNaN(c)||c>1||c<0?b:c},s=function(a,b){if(a=="true")return h;if(a=="false")return j;return b},ga=/^([\w-]+\.)*([\w-]{2,})(\:[0-9]+)?$/,t=function(a,b){if(!a)return b;var c=a.match(ga);return c?c[0]:b};var ha=function(){return t("","googleads.g.doubleclick.net")},ia=function(){return t("","pagead2.googlesyndication.com")},u=function(){return t("","pagead2.googlesyndication.com")};var v=Array.prototype,ja=v.forEach?function(a,b,c){v.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=n(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},ka=function(){return v.concat.apply(v,arguments)},la=function(a){if(m(a))return ka(a);else{for(var b=[],c=0,d=a.length;c<d;c++)b[c]=a[c];return b}};var w=function(a,b){this.width=a;this.height=b};w.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};w.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};w.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};w.prototype.scale=function(a){this.width*=a;this.height*=a;return this};var ma=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},na=["constructor","hasOwnProperty","isPrototypeOf","propertyIsEnumerable","toLocaleString","toString","valueOf"],oa=function(a){for(var b,c,d=1;d<arguments.length;d++){c=arguments[d];for(b in c)a[b]=c[b];for(var e=0;e<na.length;e++){b=na[e];if(Object.prototype.hasOwnProperty.call(c,b))a[b]=c[b]}}};var ua=function(a,b){if(b)return a.replace(pa,"&amp;").replace(qa,"&lt;").replace(ra,"&gt;").replace(sa,"&quot;");else{if(!ta.test(a))return a;if(a.indexOf("&")!=-1)a=a.replace(pa,"&amp;");if(a.indexOf("<")!=-1)a=a.replace(qa,"&lt;");if(a.indexOf(">")!=-1)a=a.replace(ra,"&gt;");if(a.indexOf('"')!=-1)a=a.replace(sa,"&quot;");return a}},pa=/&/g,qa=/</g,ra=/>/g,sa=/\"/g,ta=/[&<>\"]/,xa=function(a){if(a.indexOf("&")!=-1)return"document"in k&&a.indexOf("<")==-1?va(a):wa(a);return a},va=function(a){var b=
k.document.createElement("a");b.innerHTML=a;b.normalize&&b.normalize();a=b.firstChild.nodeValue;b.innerHTML="";return a},wa=function(a){return a.replace(/&([^;]+);/g,function(b,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if(c.charAt(0)=="#"){var d=Number("0"+c.substr(1));if(!isNaN(d))return String.fromCharCode(d)}return b}})},ya=function(a,b){for(var c=b.length,d=0;d<c;d++){var e=c==1?b:b.charAt(d);if(a.charAt(0)==e&&a.charAt(a.length-1)==
e)return a.substring(1,a.length-1)}return a},Aa=function(a,b){for(var c=0,d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=String(b).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(d.length,e.length),g=0;c==0&&g<f;g++){var o=d[g]||"",M=e[g]||"",E=new RegExp("(\\d*)(\\D*)","g"),Qb=new RegExp("(\\d*)(\\D*)","g");do{var N=E.exec(o)||["","",""],O=Qb.exec(M)||["","",""];if(N[0].length==0&&O[0].length==0)break;c=N[1].length==0?0:parseInt(N[1],10);var Rb=O[1].length==0?0:parseInt(O[1],
10);c=za(c,Rb)||za(N[2].length==0,O[2].length==0)||za(N[2],O[2])}while(c==0)}return c},za=function(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};var x,Ba,y,Ca,Da,Ea,Fa,Ga,Ha,Ia=function(){return k.navigator?k.navigator.userAgent:i},z=function(){return k.navigator},Ja=function(){Da=Ca=y=Ba=x=j;var a;if(a=Ia()){var b=z();x=a.indexOf("Opera")==0;Ba=!x&&a.indexOf("MSIE")!=-1;Ca=(y=!x&&a.indexOf("WebKit")!=-1)&&a.indexOf("Mobile")!=-1;Da=!x&&!y&&b.product=="Gecko"}};Ja();
var A=x,B=Ba,Ka=Da,La=y,Ma=Ca,Na=function(){var a=z();return a&&a.platform||""},Oa=Na(),Pa=function(){Ea=Oa.indexOf("Mac")!=-1;Fa=Oa.indexOf("Win")!=-1;Ga=Oa.indexOf("Linux")!=-1;Ha=!!z()&&(z().appVersion||"").indexOf("X11")!=-1};Pa();
var Qa=Ea,Ra=Fa,Sa=Ga,Ta=function(){var a="",b;if(A&&k.opera){a=k.opera.version;a=typeof a=="function"?a():a}else{if(Ka)b=/rv\:([^\);]+)(\)|;)/;else if(B)b=/MSIE\s+([^\);]+)(\)|;)/;else if(La)b=/WebKit\/(\S+)/;if(b)a=(a=b.exec(Ia()))?a[1]:""}return a},Ua=Ta(),Va={},C=function(a){return Va[a]||(Va[a]=Aa(Ua,a)>=0)};var Wa=function(a){return n(a)?document.getElementById(a):a},Xa=Wa,Za=function(a,b){ma(b,function(c,d){if(d=="style")a.style.cssText=c;else if(d=="class")a.className=c;else if(d=="for")a.htmlFor=c;else if(d in Ya)a.setAttribute(Ya[d],c);else a[d]=c})},Ya={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",type:"type"},$a=function(a){var b=a.document;if(La&&!C("500")&&!Ma){if(typeof a.innerHeight==
"undefined")a=window;b=a.innerHeight;var c=a.document.documentElement.scrollHeight;if(a==a.top)if(c<b)b-=15;return new w(a.innerWidth,b)}a=b.compatMode=="CSS1Compat"&&(!A||A&&C("9.50"))?b.documentElement:b.body;return new w(a.clientWidth,a.clientHeight)},bb=function(){return ab(document,arguments)},ab=function(a,b){var c=b[0],d=b[1];if(B&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',ua(d.name),'"');if(d.type){c.push(' type="',ua(d.type),'"');var e={};oa(e,d);d=e;delete d.type}c.push(">");
c=c.join("")}var f=a.createElement(c);if(d)if(n(d))f.className=d;else Za(f,d);if(b.length>2){d=function(g){if(g)f.appendChild(n(g)?a.createTextNode(g):g)};for(c=2;c<b.length;c++){e=b[c];da(e)&&!(ea(e)&&e.nodeType>0)?ja(cb(e)?la(e):e,d):d(e)}}return f},db=function(a,b){a.appendChild(b)},cb=function(a){if(a&&typeof a.length=="number")if(ea(a))return typeof a.item=="function"||typeof a.item=="string";else if(l(a)=="function")return typeof a.item=="function";return j};var eb=document,D=window,fb=function(a){var b=i;if((a=a.getElementsByTagName("script"))&&a.length){b=a[a.length-1];b=b.parentNode}return b},gb=fb(eb);u();
var F=function(a,b){for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.call(i,a[c],c,a)},hb=function(a){return!!a&&typeof a=="function"&&!!a.call},ib=function(a){return!!a&&(typeof a=="object"||typeof a=="function")},kb=function(a,b){if(!a||!ib(a))return h;return!jb(a,b.prototype)},jb=function(a,b){if(!a)return j;var c=h;F(b,function(d,e){if(!c||!(e in a)||typeof d!=typeof a[e])c=j});return c},lb=function(a){if(arguments.length<2)return a.length;for(var b=1,c=arguments.length;b<c;++b)a.push(arguments[b]);return a.length};
function G(a){return typeof encodeURIComponent=="function"?encodeURIComponent(a):escape(a)}function mb(a,b,c){var d=document.createElement("script");d.type="text/javascript";if(b)d.onload=b;if(c)d.id=c;d.src=a;var e=document.getElementsByTagName("head")[0];if(!e)return j;window.setTimeout(function(){e.appendChild(d)},0);return h}function nb(a,b){if(a.attachEvent){a.attachEvent("onload",b);return h}if(a.addEventListener){a.addEventListener("load",b,j);return h}return j}
function ob(a,b){a.google_image_requests||(a.google_image_requests=[]);var c=new Image;c.src=b;a.google_image_requests.push(c)}function pb(a){if(a in qb)return qb[a];return qb[a]=navigator.userAgent.toLowerCase().indexOf(a)!=-1}var qb={};
function rb(){if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];if(a&&a.description)return a.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else if(navigator.userAgent&&navigator.userAgent.indexOf("Windows CE")>=0){a=3;for(var b=1;b;)try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(a+1));a++}catch(c){b=i}return a.toString()}else if(pb("msie")&&!window.opera){b=i;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(d){a=
0;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");a=6;b.AllowScriptAccess="always"}catch(e){if(a==6)return a.toString()}try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(f){}}if(b){a=b.GetVariable("$version").split(" ")[1];return a.replace(/,/g,".")}}return"0"}function sb(a){var b=a.google_ad_format;if(b)return b.indexOf("_0ads")>0;return a.google_ad_output!="html"&&a.google_num_radlinks>0}function H(a){return!!a&&a.indexOf("_sdo")!=-1}
function tb(a,b){if(!(Math.random()<1.0E-4)){var c=Math.random();if(c<b){c=Math.floor(c/b*a.length);return a[c]}}return""}
var ub=function(a){a.u_tz=-(new Date).getTimezoneOffset();a.u_his=window.history.length;a.u_java=navigator.javaEnabled();if(window.screen){a.u_h=window.screen.height;a.u_w=window.screen.width;a.u_ah=window.screen.availHeight;a.u_aw=window.screen.availWidth;a.u_cd=window.screen.colorDepth}if(navigator.plugins)a.u_nplug=navigator.plugins.length;if(navigator.mimeTypes)a.u_nmime=navigator.mimeTypes.length},vb=function(a,b){var c=b||D;if(a&&c.top!=c)c=c.top;try{return c.document&&!c.document.body?new w(-1,
-1):$a(c||window)}catch(d){return new w(-12245933,-12245933)}},wb=function(a,b){var c=a.length;if(c==0)return 0;for(var d=b||305419896,e=0;e<c;e++){var f=a.charCodeAt(e);d^=(d<<5)+(d>>2)+f&4294967295}return d>0?d:4294967296+d},xb=function(a){if(a==a.top)return 0;var b=[];b.push(a.document.URL);a.name&&b.push(a.name);var c=h;a=vb(!c,a);b.push(a.width.toString());b.push(a.height.toString());return wb(b.join(""))},yb=function(a){if(!a)return"";var b=[],c=0;for(a=a;a&&c<25;a=a.parentNode,++c)b.push(a.id||
"");return b.join()};var zb={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",google_color_url:"color_url",
google_contents:"contents",google_country:"gl",google_cpm:"cpm",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_font_face:"f",google_font_size:"fs",
google_hints:"hints",google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_page_url:"url",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_tag_info:"gut",google_targeting:"targeting",google_targeting_video_doc_id:"tvdi",google_ui_features:"ui",google_ui_version:"uiv",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type"},Ab={google_ad_client:"client",google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",
google_ad_height:"h",google_ad_override:"google_ad_override",google_ad_slot:"slotname",google_ad_width:"w",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",google_rl_mode:"rl_mode",google_rt:"rt",
google_skip:"skip"},Bb={google_only_pyv_ads:"pyv",google_with_pyv_ads:"withpyv"};function Cb(a,b){try{return a.top.document.URL==b.URL}catch(c){}return j}function Db(a,b,c,d){c=c||a.google_ad_width;d=d||a.google_ad_height;if(Cb(a,b))return j;var e=b.documentElement;if(c&&d){var f=1,g=1;if(a.innerHeight){f=a.innerWidth;g=a.innerHeight}else if(e&&e.clientHeight){f=e.clientWidth;g=e.clientHeight}else if(b.body){f=b.body.clientWidth;g=b.body.clientHeight}if(g>2*d||f>2*c)return j}return h}function Eb(a,b){F(b,function(c,d){a["google_"+d]=c})}
function Fb(a,b){if(!b)return a.URL;return a.referrer}function Gb(a,b){if(!b&&a.google_referrer_url==i)return"0";else if(b&&a.google_referrer_url==i)return"1";else if(!b&&a.google_referrer_url!=i)return"2";else if(b&&a.google_referrer_url!=i)return"3";return"4"}function Hb(a,b,c,d){a.page_url=Fb(c,d);a.page_location=i}function Ib(a,b,c,d){a.page_url=b.google_page_url;a.page_location=Fb(c,d)||"EMPTY"}
function Jb(a,b){var c={},d=Db(a,b,a.google_ad_width,a.google_ad_height);c.iframing=Gb(a,d);a.google_page_url?Ib(c,a,b,d):Hb(c,a,b,d);c.last_modified_time=b.URL==c.page_url?Date.parse(b.lastModified)/1E3:i;c.referrer_url=d?a.google_referrer_url:a.google_page_url&&a.google_referrer_url?a.google_referrer_url:b.referrer;return c}function Kb(a){var b={},c=a.URL.substring(a.URL.lastIndexOf("http"));b.iframing=i;b.page_url=c;b.page_location=a.URL;b.last_modified_time=i;b.referrer_url=c;return b}
function Lb(a,b){var c=Mb(a,b);Eb(a,c)}function Mb(a,b){var c;return c=a.google_page_url==i&&Nb[b.domain]?Kb(b):Jb(a,b)}var Nb={};Nb["ad.yieldmanager.com"]=h;var Ob=r("0",0),Pb=r("0",0),Sb=r("0",0),Tb=r("1",0),Ub=r("1",0),Vb=r("1",0),Wb=r("0.01",0),Xb=r("0.01",0),Yb=r("0.01",0),Zb=r("0.008",0),$b=r("0.01",
0),ac=r("0",0);var bc=s("false",j),cc=s("false",j),dc=s("false",j),ec=s("false",j);var fc=function(a,b,c){b=p(b,k,a);a=window.onerror;window.onerror=b;try{c()}catch(d){c=d.toString();var e="";if(d.fileName)e=d.fileName;var f=-1;if(d.lineNumber)f=d.lineNumber;b=b(c,e,f);if(!b)throw d;}window.onerror=a};q("google_protectAndRun",fc);
var hc=function(a,b,c,d){if(Math.random()<0.01){var e=eb;a=["http://",ia(),"/pagead/gen_204","?id=jserror","&jscb=",bc?1:0,"&jscd=",dc?1:0,"&context=",G(a),"&msg=",G(b),"&file=",G(c),"&line=",G(d.toString()),"&url=",G(e.URL.substring(0,512)),"&ref=",G(e.referrer.substring(0,512))];a.push(gc());ob(D,a.join(""))}return!ec};q("google_handleError",hc);
var jc=function(a){ic|=a},ic=0,gc=function(){var a=["&client=",G(D.google_ad_client),"&format=",G(D.google_ad_format),"&slotname=",G(D.google_ad_slot),"&output=",G(D.google_ad_output),"&ad_type=",G(D.google_ad_type)];return a.join("")};var kc="",nc=function(){if(window.google_ad_frameborder==i)window.google_ad_frameborder=0;if(window.google_ad_output==i)window.google_ad_output="html";if(H(window.google_ad_format)){var a=window.google_ad_format.match(/^(\d+)x(\d+)_.*/);if(a){window.google_ad_width=parseInt(a[1],10);window.google_ad_height=parseInt(a[2],10);window.google_ad_output="html"}}window.google_ad_format=lc(window.google_ad_format,String(window.google_ad_output),Number(window.google_ad_width),Number(window.google_ad_height),
window.google_ad_slot,!!window.google_override_format);kc=window.google_ad_client||"";window.google_ad_client=mc(window.google_ad_format,window.google_ad_client);Lb(window,document);if(window.google_flash_version==i)window.google_flash_version=rb();window.google_ad_section=window.google_ad_section||window.google_ad_region||"";window.google_country=window.google_country||window.google_gl||"";a=(new Date).getTime();if(m(window.google_color_bg))window.google_color_bg=I(window.google_color_bg,a);if(m(window.google_color_text))window.google_color_text=
I(window.google_color_text,a);if(m(window.google_color_link))window.google_color_link=I(window.google_color_link,a);if(m(window.google_color_url))window.google_color_url=I(window.google_color_url,a);if(m(window.google_color_border))window.google_color_border=I(window.google_color_border,a);if(m(window.google_color_line))window.google_color_line=I(window.google_color_line,a)},oc=function(a){F(zb,function(b,c){a[c]=i});F(Ab,function(b,c){a[c]=i});F(Bb,function(b,c){a[c]=i});a.google_container_id=i;
a.google_eids=i;a.google_page_location=i;a.google_referrer_url=i;a.google_ad_region=i;a.google_gl=i},I=function(a,b){jc(2);return a[b%a.length]},mc=function(a,b){if(!b)return"";b=b.toLowerCase();return b=H(a)?pc(b):qc(b)},qc=function(a){if(a&&a.substring(0,3)!="ca-")a="ca-"+a;return a},pc=function(a){if(a&&a.substring(0,7)!="ca-aff-")a="ca-aff-"+a;return a},lc=function(a,b,c,d,e,f){if(!a&&b=="html")a=c+"x"+d;return a=rc(a,e,f)?a.toLowerCase():""},rc=function(a,b,c){if(!a)return j;if(!b)return h;return c};var J=document,K=navigator,L=window;
function sc(){var a=J.cookie,b=Math.round((new Date).getTime()/1E3),c=L.google_analytics_domain_name;c=typeof c=="undefined"?tc("auto"):tc(c);var d=a.indexOf("__utma="+c+".")>-1,e=a.indexOf("__utmb="+c)>-1,f=a.indexOf("__utmc="+c)>-1,g={},o=!!L&&!!L.gaGlobal;if(d){a=a.split("__utma="+c+".")[1].split(";")[0].split(".");g.sid=e&&f?a[3]+"":o&&L.gaGlobal.sid?L.gaGlobal.sid:b+"";g.vid=a[0]+"."+a[1];g.from_cookie=h}else{g.sid=o&&L.gaGlobal.sid?L.gaGlobal.sid:b+"";g.vid=o&&L.gaGlobal.vid?L.gaGlobal.vid:
(Math.round(Math.random()*2147483647)^uc()&2147483647)+"."+b;g.from_cookie=j}g.dh=c;g.hid=o&&L.gaGlobal.hid?L.gaGlobal.hid:Math.round(Math.random()*2147483647);return L.gaGlobal=g}
function uc(){var a=J.cookie?J.cookie:"",b=L.history.length,c,d=[K.appName,K.version,K.language?K.language:K.browserLanguage,K.platform,K.userAgent,K.javaEnabled()?1:0].join("");if(L.screen)d+=L.screen.width+"x"+L.screen.height+L.screen.colorDepth;else if(L.java){c=java.awt.Toolkit.getDefaultToolkit().getScreenSize();d+=c.screen.width+"x"+c.screen.height}d+=a;d+=J.referrer?J.referrer:"";for(a=d.length;b>0;)d+=b--^a++;return vc(d)}
function vc(a){var b=1,c=0,d;if(!(a==undefined||a=="")){b=0;for(d=a.length-1;d>=0;d--){c=a.charCodeAt(d);b=(b<<6&268435455)+c+(c<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function tc(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=J.domain;if("www."==a.substring(0,4))a=a.substring(4,a.length)}return vc(a.toLowerCase())};var wc=function(a){var b="google_test";try{var c=a[b];a[b]=!c;if(a[b]===!c){a[b]=c;return h}}catch(d){}return j},xc=function(a){for(;a!=a.parent&&wc(a.parent);)a=a.parent;return a},yc=i,zc=function(){yc||(yc=xc(window));return yc},Ac=function(){zc()!=window&&jc(4)};var P=function(){this.n=[];this.K=window;this.c=0},Bc=function(a,b){this.fn=a;this.win=b};P.prototype.enqueue=function(a,b){this.n.push(new Bc(a,b||this.K));this.f()};P.prototype.h=function(){this.c=1};P.prototype.o=function(){if(this.c==1)this.c=0;this.f()};fa(P.prototype,"nq",P.prototype.enqueue);fa(P.prototype,"al",P.prototype.h);fa(P.prototype,"rl",P.prototype.o);P.prototype.f=function(){this.K.setTimeout(p(this.I,this),0)};
P.prototype.I=function(){if(this.c==0&&this.n.length){var a=this.n.shift();this.c=2;a.win.setTimeout(p(this.G,this,a),0);this.f()}};P.prototype.G=function(a){this.c=0;a.fn()};var Cc=function(){var a=zc().google_jobrunner;ib(a)&&hb(a.nq)&&hb(a.al)&&hb(a.rl)&&a.rl()};var Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc=function(){Jc=Ic=Hc=Gc=Fc=Ec=Dc=j;var a=Ia();if(a)if(a.indexOf("Firefox")!=-1)Dc=h;else if(a.indexOf("Camino")!=-1)Ec=h;else if(a.indexOf("iPhone")!=-1||a.indexOf("iPod")!=-1)Fc=h;else if(a.indexOf("iPad")!=-1)Gc=h;else if(a.indexOf("Android")!=-1)Hc=h;else if(a.indexOf("Chrome")!=-1)Ic=h;else if(a.indexOf("Safari")!=-1)Jc=h};Kc();var Q=!!window.google_async_iframe_id,Lc=Q&&window.parent||window,Mc=function(a){if(Q&&a!=a.parent){Cc();a.setTimeout(function(){a.document.close()},0)}};var Nc=function(a){var b="google_unique_id";if(a[b])++a[b];else a[b]=1;return a[b]};var R=function(){this.defaultBucket=[];this.layers={};for(var a=0,b=arguments.length;a<b;++a)this.layers[arguments[a]]=""},Oc=function(a){for(var b=new R,c=0,d=a.defaultBucket.length;c<d;++c)b.defaultBucket.push(a.defaultBucket[c]);F(a.layers,p(R.prototype.j,b));return b};R.prototype.j=function(a,b){this.layers[b]=a};R.prototype.H=function(a,b){if(a=="")return"";if(!b){this.defaultBucket.push(a);return a}if(this.layers.hasOwnProperty(b))return this.layers[b]=a;return""};
R.prototype.b=function(a,b,c){if(this.v(c)&&!(Math.random()<1.0E-4)&&Math.random()<b){b=Math.floor(Math.random()*a.length);return this.H(a[b],c)}return""};R.prototype.v=function(a){if(!a)return h;return this.layers.hasOwnProperty(a)&&this.layers[a]==""};R.prototype.d=function(a){if(this.layers.hasOwnProperty(a))return this.layers[a];return""};
R.prototype.u=function(){var a=[],b=function(c){c!=""&&a.push(c)};F(this.layers,b);if(this.defaultBucket.length>0&&a.length>0)return this.defaultBucket.join(",")+","+a.join(",");return this.defaultBucket.join(",")+a.join(",")};var Qc=function(a){this.a=this.S=a;Pc(this)},Rc,S=function(){if(Rc)return Rc;if(Q)var a=Lc,b="google_persistent_state_async",c={};else{a=window;b="google_persistent_state";c=a}var d=a[b];if(typeof d!="object"||typeof d.S!="object")return a[b]=Rc=new Qc(c);return Rc=d},Pc=function(a){T(a,1,j);T(a,2,j);T(a,3,i);T(a,4,0);T(a,5,0);T(a,6,0);T(a,7,(new Date).getTime());T(a,8,{});T(a,9,{});T(a,10,{});T(a,11,[]);T(a,12,0)},Sc=function(a){switch(a){case 1:return"google_new_domain_enabled";case 2:return"google_new_domain_checked";
case 3:return"google_exp_persistent";case 4:return"google_num_sdo_slots";case 5:return"google_num_0ad_slots";case 6:return"google_num_ad_slots";case 7:return"google_correlator";case 8:return"google_prev_ad_formats_by_region";case 9:return"google_prev_ad_slotnames_by_region";case 10:return"google_num_slots_by_channel";case 11:return"google_viewed_host_channels";case 12:return"google_num_slot_to_show"}},U=function(a,b){var c=Sc(b);return c=a.S[c]},V=function(a,b,c){return a.S[Sc(b)]=c},T=function(a,
b,c){a=a.S;b=Sc(b);if(a[b]===undefined)return a[b]=c;return a[b]},Tc=function(a){if(U(a,1))return h;return V(a,1,!!window.google_new_domain_enabled)},Uc=function(a,b){return V(a,3,b)};var Vc,Wc,W=function(){if(Vc)return Vc;var a=S(),b=U(a,3);if(kb(b,R))return Vc=Uc(a,new R(1,2,3,4));return Vc=b},Xc=function(){Wc||(Wc=Oc(W()));return Wc};var Yc={google:1,googlegroups:1,gmail:1,googlemail:1,googleimages:1,googleprint:1};function Zc(a){a=a.google_page_location||a.google_page_url;if(!a)return j;a=a.toString();if(a.indexOf("http://")==0)a=a.substring(7,a.length);else if(a.indexOf("https://")==0)a=a.substring(8,a.length);var b=a.indexOf("/");if(b==-1)b=a.length;a=a.substring(0,b);a=a.split(".");b=j;if(a.length>=3)b=a[a.length-3]in Yc;if(a.length>=2)b=b||a[a.length-2]in Yc;return b}
function $c(a,b,c){var d=S();if(Zc(a))return!V(d,2,h);if(!U(d,2)){a=Math.random();if(a<=c){c="http://"+ha()+"/pagead/test_domain.js";a="script";b.write("<"+a+' src="'+c+'"></'+a+">");return V(d,2,h)}}return j}var ad=function(a){var b=W();if(b.d(1)=="44901228")return j;if(b.d(1)=="44901229"||Math.random()<Pb)return 1==Math.floor(a/2)%2;return j};
function bd(a,b){var c=S();if(!Zc(a)&&Tc(c))return ad(b)?"http://"+t("","googleads2.g.doubleclick.net"):"http://"+ha();return"http://"+ia()};var X=function(a){this.J=a;this.m=[];this.l=0;this.e=[];this.B=0;this.g=[];this.z=j;this.p=this.q="";this.w=j};X.prototype.D=function(a,b){var c=this.J[b],d=this.m;this.J[b]=function(e){if(e&&e.length>0){var f=e.length>1?e[1].url:i;d.push([a,xa(e[0].url),f])}c(e)}};X.prototype.C=function(){this.l++};X.prototype.F=function(a){this.e.push(a)};var cd="http://"+u()+"/pagead/osd.js";X.prototype.A=function(){if(!this.z){nb(D,dd);mb(cd);this.z=h}};
X.prototype.r=function(a){if(this.l>0)for(var b=document.getElementsByTagName("iframe"),c=this.w?"google_ads_iframe_":"google_ads_frame",d=0;d<b.length;d++){var e=b.item(d);e.src&&e.name&&e.name.indexOf(c)==0&&a(e,e.src)}};
X.prototype.s=function(a){var b=this.m;if(b.length>0)for(var c=document.getElementsByTagName("a"),d=0;d<c.length;d++)for(var e=0;e<b.length;e++)if(c.item(d).href==b[e][1]){var f=c.item(d).parentNode;if(b[e][2])for(var g=f,o=0;o<4;o++){if(g.innerHTML.indexOf(b[e][2])>0){f=g;break}g=g.parentNode}a(f,b[e][0]);b.splice(e,1);break}};X.prototype.t=function(a){for(var b=0;b<this.e.length;b++){var c=this.e[b],d=ed(c);if(d)(d=document.getElementById("google_ads_div_"+d))&&a(d,c)}};
X.prototype.i=function(a){this.s(a);this.t(a);this.r(a)};X.prototype.setupOsd=function(a,b,c){this.B=a;this.q=b;this.p=c};X.prototype.getOsdMode=function(){return this.B};X.prototype.getEid=function(){return this.q};X.prototype.getCorrelator=function(){return this.p};X.prototype.k=function(){return this.m.length+this.l+this.e.length};X.prototype.setValidOutputTypes=function(a){this.g=a};
X.prototype.registerAdBlockByType=function(a,b,c){if(this.g.length>0){for(var d=0;d<this.g.length;d++)if(this.g[d]==a){this.w=c;if(a=="js")this.D(b,"google_ad_request_done");else if(a=="html")this.C();else a=="json_html"&&this.F(b)}this.A()}};var ed=function(a){if((a=a.match(/[&\?](?:slotname)=([^&]+)/))&&a.length==2)return a[1];return""},dd=function(){D.google_osd_page_loaded=h},fd=function(){window.__google_ad_urls||(window.__google_ad_urls=new X(window));return window.__google_ad_urls};
q("Goog_AdSense_getAdAdapterInstance",fd);q("Goog_AdSense_OsdAdapter",X);q("Goog_AdSense_OsdAdapter.prototype.numBlocks",X.prototype.k);q("Goog_AdSense_OsdAdapter.prototype.findBlocks",X.prototype.i);q("Goog_AdSense_OsdAdapter.prototype.getOsdMode",X.prototype.getOsdMode);q("Goog_AdSense_OsdAdapter.prototype.getEid",X.prototype.getEid);q("Goog_AdSense_OsdAdapter.prototype.getCorrelator",X.prototype.getCorrelator);q("Goog_AdSense_OsdAdapter.prototype.setValidOutputTypes",X.prototype.setValidOutputTypes);
q("Goog_AdSense_OsdAdapter.prototype.setupOsd",X.prototype.setupOsd);q("Goog_AdSense_OsdAdapter.prototype.registerAdBlockByType",X.prototype.registerAdBlockByType);var gd=function(a,b){var c=a.nodeType==9?a:a.ownerDocument||a.document;if(c.defaultView&&c.defaultView.getComputedStyle)if(c=c.defaultView.getComputedStyle(a,""))return c[b];return i},hd=function(a,b){return gd(a,b)||(a.currentStyle?a.currentStyle[b]:i)||a.style[b]},id=function(a,b,c,d){if(/^\d+px?$/.test(b))return parseInt(b,10);else{var e=a.style[c],f=a.runtimeStyle[c];a.runtimeStyle[c]=a.currentStyle[c];a.style[c]=b;b=a.style[d];a.style[c]=e;a.runtimeStyle[c]=f;return b}},jd=function(a){var b=
a.nodeType==9?a:a.ownerDocument||a.document,c="";if(b.createTextRange){c=b.body.createTextRange();c.moveToElementText(a);c=c.queryCommandValue("FontName")}if(!c){c=hd(a,"fontFamily");if(A&&Sa)c=c.replace(/ \[[^\]]*\]/,"")}a=c.split(",");if(a.length>1)c=a[0];return ya(c,"\"'")},kd=/[^\d]+$/,ld=function(a){return(a=a.match(kd))&&a[0]||i},md={cm:1,"in":1,mm:1,pc:1,pt:1},nd={em:1,ex:1},od=function(a){var b=hd(a,"fontSize"),c=ld(b);if(b&&"px"==c)return parseInt(b,10);if(B)if(c in md)return id(a,b,"left",
"pixelLeft");else if(a.parentNode&&a.parentNode.nodeType==1&&c in nd){a=a.parentNode;c=hd(a,"fontSize");return id(a,b==c?"1em":b,"left","pixelLeft")}c=bb("span",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});db(a,c);b=c.offsetHeight;c&&c.parentNode&&c.parentNode.removeChild(c);return b};var Y={};function pd(a){if(a==1)return h;return!Y[a]}function qd(a,b){if(!(!a||a==""))if(b==1)if(Y[b])Y[b]+=","+a;else Y[b]=a;else Y[b]=a}function rd(){var a=[];F(Y,function(b){a.push(b)});return a.join(",")}function sd(a,b){if(m(a))for(var c=0;c<a.length;c++)n(a[c])&&qd(a[c],b)}var td=j;
function ud(a,b){var c="script";td=vd(a,b);if(!td)a.google_allow_expandable_ads=j;var d=!wd();td&&d&&b.write("<"+c+' src="http://'+u()+'/pagead/expansion_embed.js"></'+c+">");var e=$c(a,b,Vb);(d=d||e)&&pb("msie")&&!window.opera?b.write("<"+c+' src="http://'+u()+'/pagead/render_ads.js"></'+c+">"):b.write("<"+c+'>google_protectAndRun("ads_core.google_render_ad", google_handleError, google_render_ad);</'+c+">")}var Z=function(a){a=a.google_unique_id;if(typeof a=="number")return a;return 0};
function $(a){return a!=i?'"'+a+'"':'""'}var xd=function(a,b){var c=b.slice(-1),d=c=="?"||c=="#"?"":"&",e=[b];c=function(f,g){if(f||f===0||f===j){if(typeof f=="boolean")f=f?1:0;lb(e,d,g,"=",G(f));d="&"}};F(a,c);return e.join("")};function yd(){var a=B&&C("6"),b=Ka&&C("1.8.1"),c=La&&C("525");if(Ra&&(a||b||c))return h;else if(Qa&&(c||b))return h;else if(Sa&&b)return h;return j}
function wd(){return(typeof ExpandableAdSlotFactory=="function"||typeof ExpandableAdSlotFactory=="object")&&typeof ExpandableAdSlotFactory.createIframe=="function"}function vd(a,b){if(a.google_allow_expandable_ads===j||!b.body||a.google_ad_output!="html"||Db(a,b)||!zd(a)||isNaN(a.google_ad_height)||isNaN(a.google_ad_width)||!yd()||b.domain!=a.location.hostname)return j;return h}function zd(a){var b=a.google_ad_format;if(H(b))return j;if(sb(a)&&b!="468x15_0ads_al")return j;return h}
function Ad(){var a;if(D.google_ad_output=="html"&&!(sb(D)||H(D.google_ad_format))&&pd(0)){a=["6083035","6083034"];a=tb(a,ac);qd(a,0)}return a=="6083035"}function Bd(a,b){if(!(Q?Z(a)==1:!Z(a))||H(a.google_ad_format))return"";var c="",d=sb(a);if(b=="html"||d)c=tb(["36815001","36815002"],Xb);if(c==""&&(b=="js"||d))c=tb(["36815003","36815004"],Yb);if(c==""&&(b=="html"||b=="js"))c=tb(["36813005","36813006"],Zb);return c}
function Cd(){if(Q)return"";var a=fd(),b=window.google_enable_osd,c;if(b===h){c="36813006";Dd(c,a)}else if(b!==j&&pd(0)){c=a.getEid();if(c=="")(c=Bd(window,String(window.google_ad_output||"")))&&Dd(c,a);else if(c!="36815001"&&c!="36815002"&&c!="36815003"&&c!="36815004"&&c!="36813005"&&c!="36813006")c=""}if(c){qd(c,0);return c}return""}
function Dd(a,b){var c=b.getOsdMode(),d=[];switch(a){case "36815004":c=1;d=["js"];break;case "36815002":c=1;d=["html"];break;case "36813006":c=0;d=["html","js"];break}d.length>0&&b.setValidOutputTypes(d);d=S();b.setupOsd(c,a,U(d,7).toString())}
function Ed(a,b,c,d){Q||Nc(a);var e=Z(a);c=xd({ifi:e},c);c=c.substring(0,1991);c=c.replace(/%\w?$/,"");var f="script";if((a.google_ad_output=="js"||a.google_ad_output=="json_html")&&(a.google_ad_request_done||a.google_radlink_request_done))b.write("<"+f+' language="JavaScript1.1" src='+$(ba(c))+"></"+f+">");else if(a.google_ad_output=="html")if(td&&wd()){b=a.google_container_id||d||i;a["google_expandable_ad_slot"+e]=ExpandableAdSlotFactory.createIframe("google_ads_frame"+e,ba(c),a.google_ad_width,
a.google_ad_height,b)}else{e='<iframe name="google_ads_frame" width='+$(String(a.google_ad_width))+" height="+$(String(a.google_ad_height))+" frameborder="+$(String(a.google_ad_frameborder==i?"":a.google_ad_frameborder))+" src="+$(ba(c))+' marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no"></iframe>';a.google_container_id?Fd(a.google_container_id,b,e):b.write(e)}return c}function Gd(a){oc(a)}
function Hd(a){var b=Xc().d(2)=="44901217";if(!Id(b))return j;b=Ad();var c=bd(window,Z(window));a=Jd(a);b=c+Kd(a.google_ad_format,b);window.google_ad_url=xd(a,b);return h}
var Od=function(a){a.dt=aa;if(Q&&window.google_bpp)a.bpp=window.google_bpp;a.shv="r20100505";var b=S(),c=U(b,8),d=window.google_ad_section,e=window.google_ad_format,f=window.google_ad_slot;if(c[d])H(e)||(a.prev_fmts=c[d]);var g=U(b,9);if(g[d])a.prev_slotnames=g[d].toLowerCase();if(e){if(!H(e))if(c[d])c[d]+=","+e;else c[d]=e}else if(f)if(g[d])g[d]+=","+f;else g[d]=f;a.correlator=U(b,7);if(U(b,2)&&!Tc(b))a.dblk=1;if(window.google_ad_channel){c=U(b,10);d="";e=window.google_ad_channel.split(Ld);
for(f=0;f<e.length;f++){g=e[f];if(c[g])d+=g+"+";else c[g]=h}a.pv_ch=d}if(window.google_ad_host_channel){b=Md(window.google_ad_host_channel,U(b,11));a.pv_h_ch=b}if(bc)a.jscb=1;if(dc)a.jscd=1;a.frm=window.google_iframing;b=Xc().d(4);if(b=="36816001")a.adk=Nd();b=sc();a.ga_vid=b.vid;a.ga_sid=b.sid;a.ga_hid=b.hid;a.ga_fc=b.from_cookie;a.ga_wpids=window.google_analytics_uacct},Pd=function(a){var b=h;if(b=vb(b)){a.biw=b.width;a.bih=b.height}},Nd=function(){var a=[];lb(a,D.google_ad_slot,D.google_ad_format,
D.google_ad_type,D.google_ad_width,D.google_ad_height);if(gb){var b=yb(gb);b&&a.push(b)}b=0;if(a)b=wb(a.join(":"));return b.toString()},Qd=function(a){var b=xb(Lc);if(b!=0)a.ifk=b.toString()};function Md(a,b){for(var c=a.split("|"),d=-1,e=[],f=0;f<c.length;f++){var g=c[f].split(Ld);b[f]||(b[f]={});for(var o="",M=0;M<g.length;M++){var E=g[M];if(E!="")if(b[f][E])o+="+"+E;else b[f][E]=h}o=o.slice(1);e[f]=o;if(o!="")d=f}c="";if(d>-1){for(f=0;f<d;f++)c+=e[f]+"|";c+=e[d]}return c}
function Rd(){cc?W().b(["33895101"],1,3):W().b(["33895100"],Ub,3);Q?W().b(["348889069"],Tb,1):W().b(["34889070"],Sb,1);var a=["44901228","44901229"];W().b(a,Ob,1);a=["44901218","44901217"];W().b(a,$b,2);a=["36816000","36816001"];W().b(a,Wb,4)}
function Sd(){Ac();(Q?Z(window)==1:!Z(window))&&Rd();var a=Cd(),b=i,c="",d=Math.random()<0.01;if(d)if(b=window.google_async_iframe_id)b=Lc.document.getElementById(b);else{c="google_temp_span";b=Td(c)}d=Hd(b);b&&b.id==c&&(b&&b.parentNode?b.parentNode.removeChild(b):i);if(d){c=Ed(window,document,window.google_ad_url);if(a)fd().registerAdBlockByType(String(window.google_ad_output||""),c,j);Gd(window)}Mc(window)}
var Ud=function(a){F(Ab,function(b,c){a[b]=window[c]});F(zb,function(b,c){a[b]=window[c]});F(Bb,function(b,c){a[b]=window[c]})},Vd=function(a){sd(window.google_eids,1);a.eid=rd();var b=Xc().u();if(a.eid.length>0&&b.length>0)a.eid+=",";a.eid+=b};function Wd(a,b,c,d){a=hc(a,b,c,d);ud(window,document);return a}function Xd(){nc()}
function Yd(a){var b={};a=a.split("?");a=a[a.length-1].split("&");for(var c=0;c<a.length;c++){var d=a[c].split("=");if(d[0])try{b[d[0].toLowerCase()]=d.length>1?window.decodeURIComponent?decodeURIComponent(d[1].replace(/\+/g," ")):unescape(d[1]):""}catch(e){}}return b}function Zd(){var a=window,b=Yd(document.URL);if(b.google_ad_override){a.google_ad_override=b.google_ad_override;a.google_adtest="on"}}
function Fd(a,b,c){if(a)if((a=b.getElementById(a))&&c&&c.length!=""){a.style.visibility="visible";a.innerHTML=c}}
var Kd=function(a,b){var c;return c=H(a)?"/pagead/sdo?":b?"/pagead/render_iframe_ads.html#":"/pagead/ads?"},$d=function(a,b){b.dff=jd(a);b.dfs=od(a)},ae=function(a){a.ref=window.google_referrer_url;a.loc=window.google_page_location},Id=function(a){var b=S(),c=U(b,8),d=U(b,9),e=window.google_ad_section;if(H(window.google_ad_format)){if(V(b,4,U(b,4)+1)>4&&!a)return j}else if(sb(window)){if(V(b,5,U(b,5)+1)>3&&!a)return j}else{var f=V(b,6,U(b,6)+1);if(window.google_num_slots_to_rotate){jc(1);c[e]="";
d[e]="";U(b,12)||V(b,12,(new Date).getTime()%window.google_num_slots_to_rotate+1);if(U(b,12)!=f)return j}else if(!a&&f>6&&e=="")return j}return h},Jd=function(a){var b={};Ud(b);Od(b);ub(b);a&&$d(a,b);Pd(b);Qd(b);Vd(b);ae(b);b.fu=ic;return b},Td=function(a){var b=window.google_container_id,c=b&&Xa(b)||Xa(a);if(!c&&!b&&a){document.write("<span id="+a+"></span>");c=Xa(a)}return c},Ld=/[+, ]/;window.google_render_ad=Sd;function be(){if(ec&&typeof D.alternateShowAds=="function")D.alternateShowAds.call(i);else{Zd();var a=window.google_start_time;if(typeof a=="number"){aa=a;window.google_start_time=i}fc("show_ads.google_init_globals",Wd,Xd);ud(window,document)}}fc("show_ads.main",hc,be);})()
